### ISSUE TITLE
Updated doc ?

### ISSUE THREAD

**Issue by cbeyer** [jaysalvat/markitup#5]
Hi, is it possible to have the doc updated ?
I use `"markitup": "^3.0.0-0",` with yarn, it seems that https://markitup.jaysalvat.com/documentation/ is outdated.

Thanks

**Comment by jaysalvat** [comment]
Hello.
This version was experimental and I've never officially released it.
Take it as it is :)

**Comment by cbeyer** [comment]
Ok :/
I don't understand how to use dialog and bring the form values (from the dialog) to the textarea...
